r"""Interactive Discord setup wizard for the naval RP bot.

Run it once to get connected:

    .\.venv\Scripts\python.exe setup.py

What it does for you:
  1. Validates your bot token against Discord.
  2. Prints the exact invite URL (correct scopes + permissions).
  3. After you invite the bot, lists your servers and channels so you can
     pick the RP channel by number -- no hunting for IDs.
  4. Writes everything to .env.

The only thing you must fetch yourself is the bot token, from
https://discord.com/developers/applications -> your app -> Bot -> Reset Token.
(Also enable "Message Content Intent" on that same Bot tab.)
"""
import asyncio
from pathlib import Path

import discord

ENV_PATH = Path(__file__).with_name(".env")
# View Channel + Send Messages + Read Message History + Manage Webhooks
PERMISSIONS = 536939520


def _prompt(label: str, current: str = "") -> str:
    suffix = f" [{current}]" if current else ""
    return input(f"{label}{suffix}: ").strip() or current


def read_existing_env() -> dict:
    data = {}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                data[key.strip()] = value.strip()
    return data


def write_env(env: dict) -> None:
    lines = [
        "# Generated by setup.py",
        "# --- Discord ---",
        f"DISCORD_TOKEN={env.get('DISCORD_TOKEN', '')}",
        f"GUILD_ID={env.get('GUILD_ID', '')}",
        f"RP_CHANNEL_ID={env.get('RP_CHANNEL_ID', '')}",
        "",
        "# --- Local LLM (LM Studio) ---",
        f"LLM_BASE_URL={env.get('LLM_BASE_URL', 'http://127.0.0.1:1234/v1')}",
        f"LLM_MODEL={env.get('LLM_MODEL', 'google/gemma-4-31b')}",
        f"LLM_API_KEY={env.get('LLM_API_KEY', 'lm-studio')}",
        "",
        "# --- Cloud fallback (xAI) ---",
        f"XAI_API_KEY={env.get('XAI_API_KEY', '')}",
        f"XAI_BASE_URL={env.get('XAI_BASE_URL', 'https://api.x.ai/v1')}",
        f"XAI_MODEL={env.get('XAI_MODEL', 'grok-4-latest')}",
        "",
        "# --- Misc ---",
        f"STATE_FILE={env.get('STATE_FILE', 'ship_state.json')}",
        f"CHARACTERS_FILE={env.get('CHARACTERS_FILE', 'characters.yaml')}",
        "",
    ]
    ENV_PATH.write_text("\n".join(lines), encoding="utf-8")


async def validate_token(token: str) -> int:
    """HTTP-only login; returns the application (client) id for the invite URL."""
    client = discord.Client(intents=discord.Intents.none())
    try:
        await client.login(token)
        app = await client.application_info()
        return app.id
    finally:
        await client.close()


async def discover(token: str):
    """Connect to the gateway and collect (guild, postable_channels) pairs."""
    intents = discord.Intents.default()
    intents.message_content = True
    client = discord.Client(intents=intents)
    result = []

    @client.event
    async def on_ready():
        for guild in client.guilds:
            channels = [
                c for c in guild.text_channels
                if c.permissions_for(guild.me).send_messages
            ]
            result.append((guild, channels))
        await client.close()

    try:
        await client.start(token)
    finally:
        if not client.is_closed():
            await client.close()
    return result


def main() -> None:
    print("=== Naval RP Bot - Discord setup ===\n")
    env = read_existing_env()

    print("Step 1. Paste your bot token.")
    print("  https://discord.com/developers/applications -> your app -> Bot")
    print("  -> Reset Token. Enable 'Message Content Intent' on that tab too.\n")
    token = _prompt("DISCORD_TOKEN", env.get("DISCORD_TOKEN", ""))
    if not token:
        print("No token entered. Exiting.")
        return

    try:
        app_id = asyncio.run(validate_token(token))
    except discord.LoginFailure:
        print("\n[X] That token was rejected. Copy the whole token and retry.")
        return

    invite = (
        f"https://discord.com/api/oauth2/authorize?client_id={app_id}"
        f"&scope=bot+applications.commands&permissions={PERMISSIONS}"
    )
    print(f"\n[OK] Token valid. Application id: {app_id}")
    print("\nStep 2. Invite the bot with this URL (open it in your browser):\n")
    print("  " + invite + "\n")
    input("Press Enter once the bot has been added to your server...")

    print("\nConnecting to find your servers and channels...")
    try:
        guilds = asyncio.run(discover(token))
    except discord.PrivilegedIntentsRequired:
        print("\n[X] 'Message Content Intent' is off. Enable it in the Developer")
        print("    Portal (Bot tab), then run setup.py again.")
        return

    if not guilds:
        print("\n[X] The bot isn't in any server yet. Do Step 2, then rerun setup.py.")
        return

    print("\nServers the bot can see:")
    for i, (guild, _) in enumerate(guilds, 1):
        print(f"  {i}. {guild.name}  (id {guild.id})")
    guild, channels = guilds[int(_prompt("Pick a server number", "1")) - 1]

    if not channels:
        print("\n[X] No channels the bot can post in. Check its role/permissions.")
        return

    print(f"\nChannels in {guild.name}:")
    for i, channel in enumerate(channels, 1):
        print(f"  {i}. #{channel.name}  (id {channel.id})")
    channel = channels[int(_prompt("Pick the RP channel number", "1")) - 1]

    env.update({
        "DISCORD_TOKEN": token,
        "GUILD_ID": str(guild.id),
        "RP_CHANNEL_ID": str(channel.id),
    })
    write_env(env)

    print(f"\n[OK] Wrote {ENV_PATH}")
    print(f"     Server: {guild.name}  |  Channel: #{channel.name}")
    print("\nDone. Start the crew with:\n  .\\.venv\\Scripts\\python.exe bot.py")


if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        print("\nCancelled.")
