"""Generate a self-contained Oracle Cloud cloud-init script for the bot.

The project isn't a git repo, so instead of cloning we embed the runtime files
as a base64 gzip tarball plus an xAI-only .env, then have cloud-init unpack it,
build a venv, and start it under systemd. Run from anywhere:

    python deploy/make_cloud_init.py              # embed secrets from your .env (hands-off)
    python deploy/make_cloud_init.py --no-secrets # leave token/key blank (fill in via SSH)

Output: deploy/oracle-cloud-init.sh  -- paste its full contents into OCI's
"cloud-init script" / "Paste cloud-init script" box when creating the instance.
"""
import base64
import io
import pathlib
import sys
import tarfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "deploy" / "oracle-cloud-init.sh"

# The minimal set the bot needs to run on the server (no Windows launchers,
# no setup wizard, no docs).
RUNTIME_FILES = ["bot.py", "brain.py", "npcs.py", "ship.py", "config.py",
                 "characters.yaml", "requirements.txt"]

UNIT = """[Unit]
Description=Naval RP NPC Crew Bot (Discord, xAI brain)
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=300
StartLimitBurst=5

[Service]
Type=simple
User=botuser
WorkingDirectory=/opt/naval-rp-bot
ExecStart=/opt/naval-rp-bot/.venv/bin/python bot.py
Restart=always
RestartSec=5
NoNewPrivileges=true
ProtectSystem=full
ProtectHome=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
"""


def make_tarball() -> bytes:
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for name in RUNTIME_FILES:
            p = ROOT / name
            if not p.exists():
                sys.exit(f"ERROR: missing runtime file {p}")
            tar.add(p, arcname=name)  # flat names -> extract straight into the app dir
    return buf.getvalue()


def read_env() -> dict:
    env = {}
    p = ROOT / ".env"
    if p.exists():
        for line in p.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip()
    return env


def main():
    no_secrets = "--no-secrets" in sys.argv
    env = read_env()

    token = "" if no_secrets else env.get("DISCORD_TOKEN", "")
    key = "" if no_secrets else env.get("XAI_API_KEY", "")
    channels = env.get("RP_CHANNEL_ID", "")
    model = env.get("XAI_MODEL", "grok-4.3") or "grok-4.3"
    token = token or "PASTE_DISCORD_TOKEN_HERE"
    key = key or "PASTE_XAI_API_KEY_HERE"
    embedded = not no_secrets and not token.startswith("PASTE_") and not key.startswith("PASTE_")

    code_b64 = base64.b64encode(make_tarball()).decode()
    code_wrapped = "\n".join(code_b64[i:i + 76] for i in range(0, len(code_b64), 76))

    env_content = (
        f"DISCORD_TOKEN={token}\n"
        f"RP_CHANNEL_ID={channels}\n"
        "LLM_BASE_URL=\n"
        f"XAI_API_KEY={key}\n"
        "XAI_BASE_URL=https://api.x.ai/v1\n"
        f"XAI_MODEL={model}\n"
        "CONTINUITY_SECONDS=60\n"
        "STATE_FILE=ship_state.json\n"
        "LOG_FILE=chronicle.json\n"
        "CHARACTERS_FILE=characters.yaml\n"
    )

    start = ("systemctl enable --now naval-rp-bot"
             if embedded else
             "systemctl enable naval-rp-bot\n"
             'echo "Fill /opt/naval-rp-bot/.env (DISCORD_TOKEN, XAI_API_KEY), then: '
             'sudo systemctl start naval-rp-bot"')

    script = f"""#!/bin/bash
# Cloud-init for the Naval RP bot -- Oracle Cloud, Ubuntu 24.04, xAI brain.
# Generated by deploy/make_cloud_init.py. Paste the whole file into OCI's
# "cloud-init script" box (Advanced options -> Management) when creating the VM.
set -euxo pipefail
export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install -y python3 python3-venv

id botuser >/dev/null 2>&1 || useradd --system --shell /usr/sbin/nologin --home-dir /opt/naval-rp-bot botuser
mkdir -p /opt/naval-rp-bot

# --- embedded bot code (base64 gzip tarball) ---
base64 -d > /tmp/naval-app.tgz <<'B64'
{code_wrapped}
B64
tar -xzf /tmp/naval-app.tgz -C /opt/naval-rp-bot
rm -f /tmp/naval-app.tgz

# --- xAI-only .env (LLM_BASE_URL empty disables the local model) ---
cat > /opt/naval-rp-bot/.env <<'ENVEOF'
{env_content}ENVEOF
chmod 600 /opt/naval-rp-bot/.env

# --- python venv + deps ---
python3 -m venv /opt/naval-rp-bot/.venv
/opt/naval-rp-bot/.venv/bin/pip install --no-cache-dir -r /opt/naval-rp-bot/requirements.txt
chown -R botuser:botuser /opt/naval-rp-bot

# --- systemd service ---
cat > /etc/systemd/system/naval-rp-bot.service <<'UNITEOF'
{UNIT}UNITEOF
systemctl daemon-reload
{start}
echo "naval-rp-bot cloud-init complete"
"""

    OUT.write_text(script, encoding="utf-8", newline="\n")
    size = len(script.encode("utf-8"))
    print(f"Wrote {OUT}")
    print(f"Size: {size} bytes ({size/1024:.1f} KB)")
    print(f"Secrets embedded: {'YES (hands-off)' if embedded else 'NO (fill .env via SSH after boot)'}")
    if size > 30000:
        print("WARNING: larger than ~30 KB -- OCI may reject it. Tell me and I'll trim or switch approach.")


if __name__ == "__main__":
    main()
